version: '3.9'
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - pg.env
    ports:
      - "5431:5432"
    networks:
      - netw
    volumes:
      - pgvol:/var/lib/postgresql/data
  go:
    container_name: gof
    env_file:
      - app.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8300"
    depends_on:
      - pgdb
    networks:
      - netw

volumes:
  pgvol:
    external: true

networks:
  netw:
    driver: bridge
